const {chromium}=require('playwright'); const {pathToFileURL}=require('url'); const path=require('path'); const fs=require('fs'); const assert=require('assert/strict');
(async()=>{const browser=await chromium.launch({channel:'msedge',headless:true});const page=await browser.newPage(); const errors=[];page.on('pageerror',e=>errors.push(e.message));const url=pathToFileURL(path.resolve('index.html')).href;fs.mkdirSync('docs/architecture-previews',{recursive:true});const results=[];
for(const width of [1920,1440,1024,768,390])for(const theme of ['dark','light'])for(const route of ['#/','#/a-medida']){
 await page.setViewportSize({width,height:1000});await page.goto(url+route);await page.evaluate(t=>document.documentElement.dataset.theme=t,theme);await page.waitForTimeout(400);
 const header=page.locator(route==='#/'?'.home-header':'.site-header');
 const overflow=await header.evaluate(el=>[...el.querySelectorAll('*')].filter(e=>e.getClientRects().length&&e.getBoundingClientRect().right>innerWidth+1).map(e=>e.className));assert.deepEqual(overflow,[],`${width} ${route} header overflow`);
 if(width>=1100){const toggle=header.locator('.resource-toggle');await toggle.click();await assert.equal(await header.locator('.resource-panel').isVisible(),true);await toggle.press('ArrowDown');assert.equal(await page.locator(':focus').textContent(),'FUNDAE');await page.keyboard.press('ArrowDown');assert.equal(await page.locator(':focus').textContent(),'Para RRHH');await page.keyboard.press('Escape');assert.equal(await toggle.getAttribute('aria-expanded'),'false');await toggle.click();await page.mouse.click(2,300);assert.equal(await toggle.getAttribute('aria-expanded'),'false');}
 else {const button=header.locator('[data-navigation-open]');await button.click();const dialog=page.locator('#architecture-menu');assert.equal(await dialog.isVisible(),true);await dialog.locator('.resource-toggle').click();assert.equal(await dialog.locator('.resource-panel').isVisible(),true);await dialog.locator('.resource-panel a').first().focus();await page.keyboard.press('Escape');assert.equal(await dialog.isVisible(),true);await page.keyboard.press('Escape');assert.equal(await dialog.isVisible(),false);assert.equal(await button.getAttribute('aria-expanded'),'false');await button.click();await dialog.locator('.resource-toggle').click();await dialog.getByRole('link',{name:'Para RRHH',exact:true}).click();await page.waitForTimeout(100);assert.equal(await dialog.isVisible(),false);assert.equal(await page.evaluate(()=>location.hash),'#/rrhh');await page.goto(url+route);await page.evaluate(t=>document.documentElement.dataset.theme=t,theme);await page.waitForTimeout(300);}
 if(route==='#/a-medida'){ const o=await page.locator('.companies-delivery').evaluate(el=>[...el.querySelectorAll('*')].filter(e=>{let r=e.getBoundingClientRect();return r.width&&(r.right>innerWidth+1||r.left<0)}).map(e=>e.className));assert.deepEqual(o,[]);await page.locator('.companies-delivery').scrollIntoViewIfNeeded();await page.screenshot({path:`docs/architecture-previews/empresas-${width}-${theme}.png`});}
 results.push({width,theme,route});
}
await page.goto(url+'#/a-medida#como-trabajamos');await page.evaluate(()=>document.fonts.ready);await page.waitForTimeout(300);assert.equal(await page.locator('#como-trabajamos').count(),1);assert.ok(await page.locator('#como-trabajamos').evaluate(e=>Math.abs(e.getBoundingClientRect().top-parseFloat(getComputedStyle(e).scrollMarginTop)-parseFloat(getComputedStyle(document.documentElement).scrollPaddingTop))<5));assert.deepEqual(errors,[]);fs.writeFileSync('docs/architecture-previews/results.json',JSON.stringify(results,null,2));console.log('Passed 20 viewport/theme/route combinations, keyboard, mobile navigation and process permalink.');await browser.close();})().catch(e=>{console.error(e);process.exit(1)});

