// No build dependencies. Produces a portable HTML from the editable page sources.
const fs = require("node:fs");
const path = require("node:path");
const root = path.resolve(__dirname, "..");
const read = (file) => fs.readFileSync(path.join(root, file), "utf8");
function expand(source, stack = []) {
  return source.replace(/<!-- include: ([\w/.-]+) -->/g, (_, file) => {
    if (!file.startsWith("pages/partials/") || file.includes(".."))
      throw new Error("Invalid partial: " + file);
    if (stack.includes(file)) throw new Error("Circular partial: " + file);
    return expand(read(file).trim(), [...stack, file]);
  });
}
const pages = JSON.parse(read("pages/manifest.json"));
const seen = new Set();
const templates = pages
  .map(({ id, file }) => {
    if (seen.has(id)) throw new Error("Duplicate template: " + id);
    seen.add(id);
    return `<template id="${id}">\n${expand(read(file)).trim()}\n</template>`;
  })
  .join("\n");
const layout = read("pages/layout.html");
if (!layout.includes("<!-- PAGES -->"))
  throw new Error("Missing page insertion marker");
const output = layout.replace("<!-- PAGES -->", templates);
fs.writeFileSync(path.join(root, "index.html"), output);
// Lazy compatibility bundle for double-click/file:// and the original Claude host.
const downloads = JSON.parse(read("kit-rrhh/manifest.json"));
const payload = Object.fromEntries(
  downloads.map((name) => [
    name,
    fs.readFileSync(path.join(root, "kit-rrhh", name)).toString("base64"),
  ]),
);
fs.mkdirSync(path.join(root, "assets/js/generated"), { recursive: true });
fs.writeFileSync(
  path.join(root, "assets/js/generated/download-data.js"),
  "// Generated by scripts/build.cjs. Do not edit.\nwindow.LOGISTIKOS_DOWNLOAD_DATA = " +
    JSON.stringify(payload) +
    ";\n",
);
console.log(
  `Built index.html: ${pages.length} templates, ${Buffer.byteLength(output)} bytes.`,
);
